### ISSUE TITLE
Sudoku cells

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#10]
## Value statement
As a developer I want each Sudoku cell to be a component, so I have more control over each cell and I can reuse the component for each cell.

## Description
Individual cells are going to be buttons. Have a react component that returns a button element, on the Sudoku Page the 81 buttons will be created and rendered later. 

## Acceptance criteria
- [x] Have a component
- [x] Able to render buttons

## Complexity
large

## Tasks
- [x] Create basic react component for individual Cell
- [x] Write Function to render cells on Sudoku page
