### ISSUE TITLE
Sudoku rows

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#12]
## Value statement
As a developer I want to group nine cells in a row, so I have more control over how to display the full grid.

## Description
For the Sudoku grid the cells should be grouped in rows. This way it is much easier to style and arrange them.

## Acceptance criteria
- [x] Nine cells should be displayed in each row

## Complexity
medium

## Tasks
- [x] Create sample Sudoku array
- [x] Change render Function to render one row
