### ISSUE TITLE
View Highscores

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#19]
## Value statement
As a user I want to be able to view a list of highscores, so I can compare my current score to past ones.

## Description
On the main page you should be able to click on an icon to access the highscore list. 

## Acceptance criteria
- [ ] Icon on main page
- [ ] List gets created and is viewable 

## Complexity
Medium

## Tasks
- [ ] Import Icon to main page
- [ ] Create highscore page
- [ ] Load highscores from local store and display them in a list
