### ISSUE TITLE
Layout / UI for Sudoku page

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#2]
## Value statement
As a user I want to easily and with a few clicks insert the numbers, so I don't get irritated and can focus on solving the Sudoku puzzle.

## Description
The input for the Sudoku cells should be intuitive and not hinder the user. 

## Acceptance criteria
- [x] Softkeyboard of phone doesn't cover any Sudoku cells
- [x] Always have the full Sudoku visible
- [x] Individual cells must be big enough to click only the wanted cell and not any surrounding ones

## Complexity
Large

## Tasks
- [x] Research workarounds to hide or not use softkeyboard
- [x] Design UI #6
- [x] Create Sudoku page #7 #8 
- [x] Add styling for Sudoku grid
- [x] Test for acceptance criteria
