### ISSUE TITLE
Calculate and Display current score

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#20]
## Value statement
As a user I want to get points when finishing a Sudoku that adds to a score, so I see how well I am doing.

## Description
After click on "Submit" the Sudoku gets validated and, depending on the difficulty,  points get added to the score.

## Acceptance criteria
- [x] Score gets displayed on Sudoku page
- [x] Points added to score after validation

## Complexity
medium

## Tasks
- [x] Decide on how many points each difficulty should give
- [x] Save Score in local storage
- [x] Load and display score on Sudoku page

**Comment by mpagels** [comment]
+1 for this. Can not submit right now and check my Sudoku.
![Bildschirmfoto 2021-08-17 um 12 16 41](https://user-images.githubusercontent.com/54703643/129708756-cc4c7f5b-d8c4-4c19-9ddd-659d225c03eb.png)
