### ISSUE TITLE
Validate Sudoku

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#25]
## Value statement
As a user I want to be able to submit or check my solution, so I know if I solved it correct or not.

## Description
Sudoku gets validated after the user clicks on "submit".
In a later feature a summary gets shown and if solved correct points get added to a score.

## Acceptance criteria
- [x] Button to send and validate Sudoku
- [x] Feedback if solved correct or not

## Complexity
medium

## Tasks
- [x] Research how to fetch with content type application/x-www-form-urlencoded
- [x] Add button
- [x] Implement fetch and get the status of Sudoku
- [x] Display status
