### ISSUE TITLE
SudokuGrid own component

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#26]
## Value statement
As a developer I want to keep individual parts as a separate component, so everything is more structured and components are reusable.

## Description
The actual Sudoku grid is part of the Sudoku page and all the logic is placed inside the SudokuPage .js file. To make it reusable (and properly handled by react) it should be a separate component.

## Acceptance criteria
- [x] SudokuGrid is a separate file

## Complexity
medium

## Tasks
- [x] Move related functions to its own file (SudokuGrid)
- [x] "Reconnect" the grid to the page, pass down needed props
- [x] Test if displayed correct and if it still works the same
