### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#30]
## Value statement
As a user I want to get notified if the app can not load some data, so I know that the problem is not on my end.

## Description
When fetching a new Sudoku it could happen that the service is not available at that moment.
The error is just logged in the console, but the user doesn't get notified. 

## Acceptance criteria
- [ ] Visible notification if Sudoku couldn't be loaded

## Complexity
medium

## Tasks
- [ ] Decide how and where notification should be displayed
- [ ] Maybe install react-toast (if decided on using toast messages)
- [ ] Pass error state to component wherever it should be displayed
- [ ] Implement logic in error handling
- [ ] Implement logic to display notification
