### ISSUE TITLE
Delete button to remove entered numbers

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#34]
## Value statement
As a user I want to be able to delete wrong entered numbers, so I don't get confused by wrong ones in the Sudoku.

## Description
For now you can only add numbers in the cells and change them. But if the number is wrong you can not delete it, only change it. 

## Acceptance criteria
- [ ] Have a delete button on Sudoku page
- [ ] Be able to delete entered numbers

## Complexity
small

## Tasks
- [ ] Add another button to the input field
- [ ] Check for input and set it to empty, if clicked on delete. (Otherwise the value in the cell would be set to the value of the delete btn)
