### ISSUE TITLE
Create Summary Page

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#40]
## Value statement
As a player I want to have a small summary after I completed the Sudoku, so I know if my solution was correct or not and how many points I got.

## Description
If the Sudoku gets submitted and validated the user will be redirected to a summary page. Here will be a card displayed that shows "victory" or "defeat", depending if the solution was correct. Also the earned points and current score will be shown.

## Acceptance criteria
- [x] Card with infos gets shown

## Complexity
large

## Tasks
- [x] Import needed svgs
- [x] Create and style info card
- [x] Add button to go back to the map
