### ISSUE TITLE
Create Map page

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#42]
## Value statement
As a player I want to be able to select the difficulty of a Sudoku, so I  can chose which one to play.

## Acceptance criteria
- [x] Rooms (difficulty) get created randomly
- [x] Be able to select a room
- [x] Difficulty and points to earn gets shown
- [x] Sudoku of selected difficulty will be fetched 

## Complexity
high

## Tasks
- [x] Import button svgs
- [x] Create static page with select buttons 
- [x] Implement random generator
- [x] Add function to select buttons
- [x] Update view to display difficulty
- [x] Pass difficulty to header and Sudoku page
- [x] Update header and Sudoku page
