### ISSUE TITLE
Save game session data

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#45]
## Value statement
As a user I want the progress to be saved, so I come back to the game and keep playing. 

## Acceptance criteria
- [x] All necessary data is saved and loaded if there is a game in progress. 

## Complexity
large

## Tasks
- [x] Save Sudoku, initial Sudoku, difficulty and the score
- [x] Check if there is a game in progress and load needed data, instead of fetching a new Sudoku
- [x] Have alerts inform the user that there is a game in progress
