### ISSUE TITLE
Confirm dialog and selected room

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#47]
## Value statement
As a user I want to be asked if I want to submit my solution, so I don't hit submit on accident. 

## Description
When you hit "submit" you directly go to the summary page, without a warning that your Sudoku might be unfinished and you lose the game. 
When you didn't select a room, you can still start a Sudoku, which would result in an empty grid. 

## Acceptance criteria
- [x] Popup message that says to select a room if no room was selected.
- [x] Only start a new Sudoku if a room is selected or if there is a game in progress
- [x] Show confirm dialog on submit and only go to summary page if clicked on "Ok" 

## Complexity
large

## Tasks
- [x] Add confirm dialog
- [x] Add popup message if no room was selected
- [x] Add checks (if/else) so no empty grid gets loaded
