### ISSUE TITLE
Highscore

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#5]
## Value statement
As a competitive user I want to get a highscore, so I can compare myself to others and compete with others.

## Acceptance criteria
- [x] Get points for solved Sudoku
- [x] Score is saved and displayed
- [ ] Score gets added to Highscore list when game is over
- [ ] List of Highscores is created and viewable

## Complexity
Medium

## Tasks
- [x] Calculate and display score #20 
- [x] Create Highscore page #19 
- [ ] Create array for Highscores and save in local storage
- [ ] Update list of Highscores if game is over
