### ISSUE TITLE
Figma Design

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#6]
## Description
Design App in Figma and post in design channel in Slack

## Timebox
Should be done by Monday afternoon.

## Tasks
- [ ] Research potential Sudoku designs
- [ ] Research typical colours for dungeon crawler games
- [ ] Make list of features
- [ ] Design individual Pages of App
- [ ] Post design in Slack channel
