### ISSUE TITLE
Sudoku Page

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#7]
## Description
Page where the actual Sudoku puzzle gets displayed 

## Timebox
Should be done until end of week

## Tasks
- [x] Research how to create Sudoku grid in react
- [x] Test grid in codepen
- [x] Test if input works
- [x] Fetch random generated Sudoku and display in grid
- [x] Add input #8 
- [x] Save user input in array
- [x] Add submit button
- [x] Send and validate Sudoku on btn click
- [ ] Display difficulty of Sudoku
