### ISSUE TITLE
Number selection on Sudoku page

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#8]
## Description
Numbers should be inserted with a special number selection field rather than with the keyboard.

## Timebox
Should be done by the end of week

## Tasks
- [x] Add Buttons and test input
- [x] Connect number selection to Sudoku field
- [x] Import design from Figma
- [x] Test selection
