### ISSUE TITLE
Setup deployment

### ISSUE THREAD

**Issue by patrikglanemann** [patrikglanemann/capstone-project#9]
## Value statement
As a developer and code reviewer I want to see the running App, so I can easily test it.

## Description
Continuous and automated deployment makes it easier to test each new version of the app. 

## Acceptance criteria
- [x] Main branch deployed to Vercel
- [x] Each PR should have a link to Vercel to see new version

## Complexity
Small

## Tasks
- [x] Set up Vercel
- [x] Deploy main branch 
- [x] Test generated link
